---
output:
  pdf_document: default
  html_document: default
---
# 2023-05-22 N2-Barcode Drug Pressure
## Drug Diltutions

Make 1$\mu$M working stock of each drug  
    * Doxorubicin: 1$\mu$L 10mM stock in 10mL media  
    * Methotrexate: 1$\mu$L 10mM stock in 10mL media  
    * Vincristine: 333.33$\mu$L 30mM stock in 10mL media    

## Doxorubicin  
    
  |Drug        |Drug ID|Dilution volume         |Media Volume | [Final Drug]|
|:---------: |:-----:| :---------------------:| :----------:|:------------|
|Doxorubicin | Dox 1 | 3600 $\mu$L (from WS)   | 8400 $\mu$L | 300nm       |
|Doxorubicin | Dox 2 | 6000 $\mu$L (from Dox 1)| 6000 $\mu$L | 150nm       |
|Doxorubicin | Dox 3 | 6000 $\mu$L (from Dox 2)| 6000 $\mu$L | 75nm        |
|Doxorubicin | Dox 4 | 6000 $\mu$L (from Dox 3)| 6000 $\mu$L | 37.5nm      |
|Doxorubicin | Dox 5 | 6000 $\mu$L (from Dox 4)| 6000 $\mu$L | 18.75nm     |


## Methotrexate  

|Drug         |Drug ID |Dilution volume         |Media Volume | [Final Drug]|
|:---------:  |:-----: | :---------------------:| :----------:|:------------|
|Methotrexate | Meth 1 | 1200 $\mu$L (from WS)    | 10800 $\mu$L | 100nm     |
|Methotrexate | Meth 2 | 6000 $\mu$L (from Meth 1)| 6000 $\mu$L |50nm       |
|Methotrexate | Meth 3 | 6000 $\mu$L (from Meth 2)| 6000 $\mu$L | 20nm      |
|Methotrexate | Meth 4 | 6000 $\mu$L (from Meth 3)| 6000 $\mu$L | 10nm      |
|Methotrexate | Meth 5 | 6000 $\mu$L (from Meth 4)| 6000 $\mu$L |5nm        |

## Vincristine

|Drug        |Drug ID|Dilution Volume |Media Volume | [Final Drug]|
|:---------: |:-----:| :------------------:| :----------:|:------------|
|Vincristine | Vin 1 | 48 $\mu$L (from WS)     | 11952 $\mu$L | 4nm       |
|Vincristine | Vin 2 | 6000 $\mu$L (from Vin 1)| 6000 $\mu$L | 2nm        |
|Vincristine | Vin 3 | 6000 $\mu$L (from Vin 2)| 6000 $\mu$L | 1nm        |
|Vincristine | Vin 4 | 6000 $\mu$L (from Vin 3)| 6000 $\mu$L | 0.5nm      |
|Vincristine | Vin 5 | 6000 $\mu$L (from Vin 4)| 6000 $\mu$L | 0.25nm     |

# Instructions
1. Make drug dilutions and DMSO tubes (3$\mu$L DMSO in 30mL)   
2. Collect wells into labeled 15mL tubes  
3. Count cells  
4. Spin down volume of CS which $\le$ 1.0x10^6^  
5. Resuspend in associated drug mix and add back to well  
